import React from "react";
import {interpolate,useCurrentFrame} from "remotion";
import type {EpisodeManifest,LearningPoint,ResolvedScene,Scene,Utterance} from "../contracts/types";
import {base,COLORS,headerStyle,mainArea,subtitleArea} from "./styles";

type Props={manifest:EpisodeManifest;scene:Scene;resolved:ResolvedScene};
const getU=(m:EpisodeManifest,id:string):Utterance|undefined=>m.utterances.find(i=>i.id===id);
const getP=(m:EpisodeManifest,id:string):LearningPoint|undefined=>m.learningPoints.find(i=>i.id===id);
const activeU=(g:number,r:ResolvedScene):string|null=>[...r.audioEvents].filter(e=>e.startFrame<=g).sort((a,b)=>b.startFrame-a.startFrame)[0]?.utteranceId??null;
const activeCue=(g:number,r:ResolvedScene)=>r.cues.find(c=>c.startFrame<=g&&g<c.endFrame);
const phase=(g:number,r:ResolvedScene)=>r.phases.find(p=>p.startFrame<=g&&g<p.endFrame)?.name??"normal";
const currentReveal=(g:number,r:ResolvedScene,ids:string[]):Set<string>=>{const starts=new Map(r.audioEvents.map(e=>[e.utteranceId,e.startFrame]));const eligible=ids.map(id=>({id,frame:starts.get(id)})).filter((x):x is {id:string;frame:number}=>x.frame!==undefined&&x.frame<=g);if(!eligible.length)return new Set();const max=Math.max(...eligible.map(x=>x.frame));return new Set(eligible.filter(x=>x.frame===max).map(x=>x.id));};
const focus=(on:boolean):React.CSSProperties=>({borderColor:on?COLORS.accent:COLORS.line,borderWidth:on?5:2,opacity:on?1:.66,fontWeight:on?650:500,transform:on?"scale(1.02)":"scale(1)"});

const Highlight=({text,phrase}:{text:string;phrase:string})=>{const i=text.toLowerCase().indexOf(phrase.toLowerCase());if(i<0)return <>{text}</>;return <>{text.slice(0,i)}<span style={{color:COLORS.accent,textDecoration:"underline",fontWeight:700}}>{text.slice(i,i+phrase.length)}</span>{text.slice(i+phrase.length)}</>;};

export const SceneRenderer:React.FC<Props>=({manifest,scene,resolved})=>{const f=useCurrentFrame(),g=resolved.startFrame+f,uid=activeU(g,resolved),cue=activeCue(g,resolved),ph=phase(g,resolved);const opacity=interpolate(f,[0,8],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});const y=interpolate(f,[0,8],[12,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});const gloss=scene.glossLearningPointId?getP(manifest,scene.glossLearningPointId):undefined;const showGloss=Boolean(gloss&&uid===gloss.sourceUtteranceId&&scene.role==="story");let visual:React.ReactNode=null;
if(scene.visual.type==="card")visual=<div style={{border:`2px solid ${COLORS.line}`,borderRadius:28,padding:"56px 72px",maxWidth:1500,textAlign:"center",background:"rgba(255,255,255,.64)"}}><div style={{fontSize:84,lineHeight:1.2,fontWeight:650}}>{scene.visual.headline}</div>{scene.visual.body?<div style={{fontSize:48,lineHeight:1.3,marginTop:40,color:COLORS.muted}}>{scene.visual.body}</div>:null}</div>;
if(scene.visual.type==="metric")visual=<div style={{textAlign:"center"}}><div style={{fontSize:56,fontWeight:600}}>{scene.visual.label}</div><div style={{display:"flex",alignItems:"baseline",justifyContent:"center",gap:24,marginTop:24}}><div style={{fontSize:144,fontWeight:700,color:COLORS.accent}}>{scene.visual.value}</div><div style={{fontSize:48,fontWeight:600}}>{scene.visual.unit}</div></div><div style={{fontSize:32,marginTop:20,color:COLORS.warning}}>{scene.visual.qualifier}</div></div>;
if(scene.visual.type==="chain"){const a=currentReveal(g,resolved,scene.visual.nodes.map(n=>n.revealAtUtteranceId));visual=<div style={{display:"flex",alignItems:"center",justifyContent:"center",width:"100%",gap:48}}>{scene.visual.nodes.map((n,i)=><React.Fragment key={`${n.label}-${i}`}><div style={{width:320,minHeight:160,border:`2px solid ${COLORS.line}`,borderRadius:22,display:"flex",alignItems:"center",justifyContent:"center",padding:24,textAlign:"center",fontSize:52,lineHeight:1.25,background:COLORS.white,...focus(a.has(n.revealAtUtteranceId))}}>{n.label}</div>{i<scene.visual.nodes.length-1?<div style={{fontSize:52,color:COLORS.muted}}>→</div>:null}</React.Fragment>)}</div>;}
if(scene.visual.type==="compare"){const a=currentReveal(g,resolved,scene.visual.rows.map(r=>r.revealAtUtteranceId));visual=<div style={{width:1600}}><div style={{display:"grid",gridTemplateColumns:"300px 1fr 1fr",gap:28,fontSize:42,fontWeight:650,marginBottom:18}}><div/><div style={{textAlign:"center"}}>{scene.visual.leftTitle}</div><div style={{textAlign:"center"}}>{scene.visual.rightTitle}</div></div>{scene.visual.rows.map((r,i)=><div key={`${r.aspect}-${i}`} style={{display:"grid",gridTemplateColumns:"300px 1fr 1fr",gap:28,minHeight:128,alignItems:"center",borderTop:`2px solid ${COLORS.line}`,fontSize:44,...focus(a.has(r.revealAtUtteranceId))}}><div style={{fontWeight:650}}>{r.aspect}</div><div style={{textAlign:"center"}}>{r.left}</div><div style={{textAlign:"center"}}>{r.right}</div></div>)}</div>;}
if(scene.visual.type==="timeline"){const a=currentReveal(g,resolved,scene.visual.events.map(e=>e.revealAtUtteranceId));visual=<div style={{width:1580}}><div style={{height:4,background:COLORS.line,margin:"0 100px 40px"}}/><div style={{display:"grid",gridTemplateColumns:`repeat(${scene.visual.events.length},1fr)`,gap:32}}>{scene.visual.events.map((e,i)=><div key={`${e.dateLabel}-${i}`} style={{border:`2px solid ${COLORS.line}`,borderRadius:20,padding:28,textAlign:"center",minHeight:190,background:COLORS.white,...focus(a.has(e.revealAtUtteranceId))}}><div style={{fontSize:30,color:COLORS.warning,fontWeight:650}}>{e.dateLabel}</div><div style={{fontSize:46,lineHeight:1.25,marginTop:18}}>{e.label}</div></div>)}</div><div style={{fontSize:32,color:COLORS.muted,textAlign:"center",marginTop:24}}>Not to scale</div></div>;}
if(scene.visual.type==="phrase"){const p=getP(manifest,scene.visual.learningPointId),source=p?getU(manifest,p.sourceUtteranceId):undefined;visual=p?<div style={{width:1580,textAlign:"center"}}><div style={{fontSize:84,lineHeight:1.22,fontWeight:600}}><Highlight text={source?.text??p.phrase} phrase={p.phrase}/></div><div style={{fontFamily:"'Noto Sans JP',sans-serif",fontSize:48,marginTop:44,color:COLORS.muted}}>{p.meaningJa}</div></div>:null;}
if(scene.visual.type==="retrieval"){const reveal=ph==="reveal"||ph==="answer";visual=<div style={{width:1500,textAlign:"center"}}><div style={{fontSize:56,fontWeight:650}}>{scene.visual.question}</div><div style={{display:"flex",gap:44,justifyContent:"center",marginTop:62}}>{scene.visual.options.map((o,i)=>{const ok=reveal&&i===scene.visual.correctIndex;return <div key={o} style={{width:560,padding:"34px 30px",borderRadius:20,border:`4px solid ${ok?COLORS.accent:COLORS.line}`,fontSize:48,fontWeight:ok?700:550,background:COLORS.white}}>{ok?"✓ ":""}{o}{ok?" · Correct":""}</div>;})}</div><div style={{fontSize:34,marginTop:42,color:COLORS.muted}}>{ph==="prompt"?"Listen for the reason.":ph==="think"?"3 · 2 · 1":ph==="answer"?scene.visual.answerJa:""}</div></div>;}
if(scene.visual.type==="recap"){const idx=Math.max(0,scene.utteranceIds.indexOf(uid??"")),pid=scene.visual.learningPointIds[Math.min(idx,2)],p=getP(manifest,pid);visual=p?<div style={{textAlign:"center"}}><div style={{fontSize:84,fontWeight:700,color:COLORS.accent}}>{p.phrase}</div><div style={{fontFamily:"'Noto Sans JP',sans-serif",fontSize:48,marginTop:34}}>{p.meaningJa}</div></div>:null;}
return <div style={{...base,position:"relative",width:"100%",height:"100%",overflow:"hidden"}}><div style={headerStyle}><span>{scene.role==="story"?scene.beat?.toUpperCase():scene.role.toUpperCase()}</span><span>{manifest.category.replace("_"," ")}</span></div><div style={{...mainArea,opacity,transform:`translateY(${y}px)`}}>{visual}</div>{showGloss&&gloss?<div style={{position:"absolute",left:144,top:656,width:1632,textAlign:"center",fontFamily:"'Noto Sans JP',sans-serif",fontSize:40,color:COLORS.warning,fontWeight:700}}>{gloss.phrase} = {gloss.meaningJa}</div>:null}<div style={subtitleArea}>{cue?<div>{cue.text}<div style={{height:6,background:COLORS.accent,borderRadius:6,marginTop:14}}/></div>:null}</div><div style={{position:"absolute",left:144,top:988,width:1632,fontSize:26,color:COLORS.muted}}>{manifest.kind==="fixture"?"FIXTURE · not for publication":`As of ${manifest.asOf}`}</div></div>;
};
